services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=promtior-rag
      - ENVIRONMENT=${ENVIRONMENT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./splits:/app/splits

  ssl-init:
    image: alpine
    volumes:
      - ./init-ssl.sh:/init-ssl.sh:ro
      - ./certs:/certs
    command: sh -c "apk add --no-cache openssl && chmod +x /init-ssl.sh && /init-ssl.sh"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    restart: always
